name: Sync Fork

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: master
          head: master
